name: Terraform Testing

on:
  push:
    branches:
      - main
    paths: 
      - "modules/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: false 
          format: csv
          
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=$(echo "${{ steps.get_changed.outputs.changed }}" | sed 's|^\(modules/[^/]*\).*|\1|')" >> $GITHUB_ENV
      
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"
          
      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }} | sed 's|^\(modules/[^/]*\).*|\1|'
        
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: ${{ env.action_state }}/
        
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.action_state }}/

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.action_state }}/
        
